### ISSUE TITLE
Workflow for assignments that are cumulative

### ISSUE THREAD

**Issue by cledwyn** [education/guide#25]
My course has assignments are are cumulative and fairly open ended.  for example 

1. Write a php page that queries a mysql db and searches for results.
2. Using work from (1.), convert search to AJAX
3, Keep same AJAX front end and swap backend from PHP to .net
4. etc.

would the #24 idea of One Repo per Assignment still hold, or would it be better to make branches within one repo.  Or tags?

**Comment by johndbritton** [comment]
My recommendation would be to have a repo for the student or group and have them submit a pull request for each iteration of the project throughout the semester (all within one repository).

Hope that helps.
