### ISSUE TITLE
Private Repo request for student

### ISSUE THREAD

**Issue by emn367** [education/guide#27]
My student request for a discount has been pending over a month. Is my email not eligible?

**Comment by emn367** [comment]
![capture](https://cloud.githubusercontent.com/assets/11743831/7906233/d1258eb8-07ec-11e5-95e4-d374b279297b.JPG)
My student request for a discount has been pending over a month. Is my email not eligible?

**Comment by michaelaye** [comment]
Oh, I guess I shouldn't expect this to be ready in a month then, either.

**Comment by johndbritton** [comment]
@michaelaye If you're having issues with the discount, please contact us here: https://education.github.com/contact
