### ISSUE TITLE
Where is the option "I don't have a school-issued email" on the website?

### ISSUE THREAD

**Issue by lvxiaoxin** [education/guide#35]
As my school email address is not being recognized by the Student Developer Pack application as a valid school address, I have to find the option to upload the  photo of proof of enrollment. But I didn't find the option on the website. Where is it?

**Comment by SalihKARAHAN** [comment]
:+1: Yes, where is * option? :angry:

**Comment by tarebyte** [comment]
@lvxiaoxin @SalihKARAHAN if you go through https://education.github.com and on the personal details page there is a select field for your school email.

This is the page

![screen shot 2016-03-10 at 9 54 50 am](https://cloud.githubusercontent.com/assets/564113/13673240/3280e232-e6a6-11e5-91bf-b029a1b13fdb.png)

You can select "I don't have a school-issued email address" and the following form will drop down

![screen shot 2016-03-10 at 9 54 59 am](https://cloud.githubusercontent.com/assets/564113/13673273/4df09bd4-e6a6-11e5-8ca7-d2034911f133.png)

This will allow you to upload your id.

Hope this helps!

**Comment by 0xad1onchain** [comment]
Thanks a lot
