### ISSUE TITLE
PULL REQUEST!!!!!

### ISSUE THREAD

**Issue by thecodingfaculty** [education/guide#37]
I have around 27 courses, how can I structure my classroom?  I have classroom with private assignments
My idea....

1. Classroom with 27 assignments, which will consist on my 27 courses project files.....does this sound right? 

2. When I give the invitation link to the assignments, the students sign up and get a copy of the original files, but cannot make pull requests to the original since they can't even see it.

Any help would be appreciated! Thanks

**Comment by tarebyte** [comment]
@thecodingfaculty I would ask in our [GitHub Education Community](https://education.github.community/).

There are a lot of teachers there that will be able to give you advice.

Thanks!
