### ISSUE TITLE
How to enable Travis-CI for Classroom

### ISSUE THREAD

**Issue by thismlguy** [education/guide#39]
Hello, 

I am a Teaching Assistant at Columbia University. How can I allow the students to enable Travis-CI integration with their repositories?

The repositories are private and travis-ci.com is not able to sync them even after they fork the repositories.

Thanks,
Aarshay

**Comment by mozzadrella** [comment]
Hi @aarshayj. As a teacher you can set up your assignments in classroom with an automated testing framework.

Are you using travisci.org or travisci.com? If you use travisci.com + sign in with your account connected to GitHub Education, then integrate testing with each individual assignment, you should be set. 

There's [a thread on our Community forums](https://education.github.community/t/blog-post-proposal-automated-grading-via-travis-ci/3118) dedicated to connecting testing frameworks and Classroom that you might find helpful. 

Please ask follow up questions there so others can learn from your implementation.
